Algoritmo "Idade daqui 30 anos"
// Escrever um programa que permita receber
//o nome e a idade de uma pessoa e em
//seguida, informar o nome digitado
//e a idade da pessoa daqui a 30 anos.
Var
nome: caracter
idade, calc: inteiro

Inicio
escreva ("Escreva seu nome: ")
leia (nome)
escreva (nome, ", qual sua idade: ")
leia (idade)
calc <- idade + 30
escreva (nome, ", sua idade daqui 30 anos é: ", calc)

Fimalgoritmo