Algoritmo "MULTIPLICAÇÃO"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 

Var

n1, n2, n3, calc: real

Inicio

Escreva ("Digite o PRIMEIRO número: ")
leia (n1)
Escreva ("Digite o SEGUNDO número: ")
leia (n2)
Escreva ("Digite o TERCEIRO número: ")
leia (n3)
calc <-  n1*n2*n3
Escreval ("A multiplicação entre os números digitados é: ", calc)

Fimalgoritmo